### ISSUE TITLE
Features timbriche con volume al minimo

### ISSUE THREAD

**Issue by francescocretti** [Dreamo-Italy/video_structure#13]
Le features timbriche (centroide spettrale, complessità spettrale, COBE, EBF) hanno valori anomali.

Questo è probabilmente dovuto al fatto che i campioni in quel caso hanno valore molto piccolo (ordine di 10^-6) e non sono mai a 0.

Idee:
- implementare un controllo del volume (c'è già) che sotto una certa soglia non calcola più l'FFT o la forza a zero.

Che ne pensi @Screeen ?

**Comment by Screeen** [comment]
La soluzione più semplice mi sembra calcolare le varie features solo se not (isSilence())
